### ISSUE TITLE
Support directory encryptions and decryption

### ISSUE THREAD

**Issue by mastercyb** [brxken128/dexios#50] opened 2022-06-07 04:34 UTC
I want to encrypt and decrypt git repo and as result to have one encryption file
How would I do it?

**Comment by brxken128** [comment] 2022-06-07 07:03
I'd recommend using an external tool such as `tar` on Linux.

You may also use 7zip/WinRAR/other alternatives on Windows, just be sure to disable compression. l

On Linux, you may use `tar -cf repo.tar git-repo/`. This will create an archive of your `git-repo` directory with no compression, which is ideal for encryption.

After you have your archive, you can run `dexios -e repo.tar repo.tar.enc` to encrypt, and `dexios -d repo.tar.enc repo.tar` to decrypt.

**Comment by brxken128** [comment] 2022-06-07 17:35
I'd just like to note that Dexios had this feature, prior to v8.4.0. I wasn't happy with the implementation and it complicated things a lot, but once v8.5.0 has been finalized, I won't be against re-introducing it.

**Comment by mastercyb** [comment] 2022-06-08 03:54
I started to dig into archivation tool in rust ecosystem and came to a [https://github.com/vach] robust solution.

**Comment by brxken128** [comment] 2022-06-08 06:44
> I started to dig into archivation tools in rust ecosystem and came to a [vach](https://github.com/vach). Seems like a modern and robust solution. It have snappy which seems like a good default compression balancing between size and speed

It does, but it locks us into that crate and specific implementation.

With a more generic zip/tar implementation, we have flexibility and we can remove it from the code without incrementing the MAJOR version (as people can just decrypt normally, and it'll be a `.zip` file).

Thank you :)

**Comment by brxken128** [comment] 2022-06-09 16:46
Hey!

I've added this feature, and you may download v8.6.0 and try it out for yourself!

File metadata is not preserved - this is a limitation with `zip-rs` - we could use `tar-rs` in future, but I wanted to get this feature implemented for you. Permissions aren't preserved either, and symlinks aren't followed - I plan to fix these in later versions. For now, I hope this is adequate.

You may encrypt your git repo with `dexios pack -r --hidden git-repo/ git.enc`, and you can unpack it with `dexios unpack git.enc .`

`-r` signifies you are running `pack` recursively, and `--hidden` includes all hidden files and folders.

You may pass `--erase` also, to securely erase your git repo (use this at your own risk!) Alternatively, you can just run `rm -rf git-repo` from the terminal.

The directory will be extracted into your current directory.

I hope this covers everything, and if you have any other features you'd like to see, please don't hesitate to ask!

Thank you :)

**Comment by brxken128** [comment] 2022-06-10 11:47
Hey @mastercyb, please could you confirm this is what you were after? Thank you :)

**Comment by mastercyb** [comment] 2022-06-11 08:45
Hi! I've tested and it seems that output does not contain any files

<img width="569" alt="Screen Shot 2022-06-11 at 8 44 09 AM" src="https://user-images.githubusercontent.com/410789/173180680-873231cf-a5eb-4d4d-8d96-5620820aaeb9.png">

<img width="569" alt="Screen Shot 2022-06-11 at 8 44 33 AM" src="https://user-images.githubusercontent.com/410789/173180690-20774f40-28f8-4548-b622-3d687eefd027.png">

<img width="466" alt="Screen Shot 2022-06-11 at 8 45 29 AM" src="https://user-images.githubusercontent.com/410789/173180718-8a0a466b-79da-41d2-a0ed-7f38e22d00ab.png">

**Comment by brxken128** [comment] 2022-06-11 09:31
> Hi! I've tested and it seems that output does not contain any files
> 
> <img width="569" alt="Screen Shot 2022-06-11 at 8 44 09 AM" src="https://user-images.githubusercontent.com/410789/173180680-873231cf-a5eb-4d4d-8d96-5620820aaeb9.png">
> 
> <img width="569" alt="Screen Shot 2022-06-11 at 8 44 33 AM" src="https://user-images.githubusercontent.com/410789/173180690-20774f40-28f8-4548-b622-3d687eefd027.png">
> 
> <img width="466" alt="Screen Shot 2022-06-11 at 8 45 29 AM" src="https://user-images.githubusercontent.com/410789/173180718-8a0a466b-79da-41d2-a0ed-7f38e22d00ab.png">
> 
> What could I do wrong?

Hi! This is indeed a rather odd issue, I'm quite confused as to how it would happen.

Could you run `dexios decrypt example.enc example.zip` and open the created zip file as normal please? I wonder if something weird has happened with the paths inside :)

**Comment by brxken128** [comment] 2022-06-11 14:36
@mastercyb Hey, I think this was fixed in v8.6.1

I did some testing and I wasn't able to reproduce the issue specified, it may be a platform-specific bug.

Due to how our file indexing implementation works, I'd recommend `packing` the folder from within the parent.

This means that you should `cd` into the git directory, and run `dexios pack example/ example.enc`. From here, you may move `example.enc` to anywhere you desire.

v8.6.1 removed the need for `--hidden`, and they are now included by default.

Your commands should be as follows:

1. `cd ~/git`
2. `dexios pack example/ example.enc`
3. `mv example.enc ~/temp/`
4. `cd ~/temp`
5. `dexios unpack example.enc .`

This will unpack the example git repo into the `~/temp` directory. Item `4` probably isn't necessary, and you can replace the `.` in item `5`, but I'm just trying to make sure it works.

If this doesn't work, I'd probably suggest taking a look inside the zip file itself (by running `dexios decrypt` on it), and seeing if the contents are as you expect.

To weed out any further issues, I also decided to recreate the file structure **fully** before extracting any files. This shouldn't have been an issue to begin with, but it could possibly help.

I truly apologise for any inconvenience, and I hope this resolves your issues. Feel free to comment here if you're still having any. Thank you :)

**Comment by brxken128** [comment] 2022-06-11 16:15
I come with great news, @mastercyb

This was fixed **fully** in v8.6.2! I managed to reproduce your issue on Windows, and from there I took a look into the zip file that was created. It appears as though the `zip` crate wasn't handling backslashes in a polite manner, and was instead treating them as some weird symbol.

I've merged a patch for this, and published it to crates.io - I'll create a release and upload the binaries as well.

I have fully tested both `pack` and `unpack` on Windows (which I think is your OS), and it all works as intended. I would still recommend `pack`ing from the parent directory, as that will clean up paths within the zip file.

Once again, I apologise for the inconvenience and I hope this fix is what you were after. File permissions and metadata are still not preserved, but `git` doesn't care about those much anyway I believe. The lack of metadata is a limitation of the `zip` crate, but I don't think there are any better alternatives for what we need.

I think this covers everything. Again, if any issues persist, please do not hesitate to reply here. I'll leave this open for a couple days just in case.

Thank you.

**Comment by mastercyb** [comment] 2022-06-12 04:12
Yep! Works now :-) Thank you!
Don't you think that pack and unpack could be merged with encrypt and decrypt, so that dexios could detect folders automatically?

**Comment by brxken128** [comment] 2022-06-12 06:48
> Yep! Works now :-) Interesting enough that my problem was on osx 12.4, not on windows. Thank you!
> Don't you think that pack and unpack could be merged with encrypt and decrypt, so that dexios could detect folders automatically?
> Because given encrypted file I should somehow detect which command to use. So unpacking become not obvious operation
> To be honest I liked the simplicity of commands in dexios without adding complexity

I'm afraid this makes things a bit harder.

For pack mode, we'd have to add the command-line arguments to `encrypt`, but specify that they can only be ran against a directory. That's not too bad.

For unpacking, we run into the issue of not knowing if the file was intended to be unpacked, or if it was just an encrypted zip file. One way I can see around this is by adding a marker within the header to signify that it was packed with Dexios.

I'll figure out the logistics later today, but none of it seems too far-fetched in all honesty.

I think this could be a good improvement.

**Comment by mastercyb** [comment] 2022-06-12 08:13
My etherean and monerujo cheers...

**Comment by brxken128** [comment] 2022-06-12 08:55
> My etherean and monerujo cheers...

Thank you so much!

It's been a pleasure working with you on this :)

**Closed** 2022-06-17 09:13 UTC
Labels: enhancement
